# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

# Samples for required secrets to be used in development and ci using prod profile.

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: gzgpGyMLJesLXt1IS/g4GL3NwteWK2Ul2TGHKpnPkRz6oVR/80/XUgYh1GTRl/1dmScIx2rJ6/rJoPc9Bm/KHA==

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: melit-market
    password: 1234
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: melit-market
    password: 1234
