# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTFkOTdkNTVjOTY1MWVmMGVmMGY4ODgyODkxZjk3YTJjZDgwZjdkYTIyZTM1Y2Q0M2E4NjU2ODAyZmYxZjdlMDBjNDkwYTJjOGNhY2EwNmQ4N2I1MTdiODUwMGM4YTcyZTMzNTJiOGUzZTYxNDRkMDkxMDBjN2ZmMTgxZjNhYmM=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: melit-market
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
